[supabase]
url = "https://cyzdezqkeyaowmfxbssb.supabase.co"
service_role_key = "ISI_SERVICE_ROLE_KEY_ANDA"

[storage]
public_base_url = "https://cyzdezqkeyaowmfxbssb.supabase.co/storage/v1/object/public/labora-documents"

[[auth.users]]
username = "admin"
password = "labora123"
role = "Admin"

[[auth.users]]
username = "reviewer"
password = "review123"
role = "Reviewer"