create extension if not exists pgcrypto;

create table if not exists dokumen_inti (
  id_dokumen text primary key,
  kategori text not null,
  kode text not null unique,
  judul_dokumen text not null,
  versi text not null default '1.0',
  status text not null,
  penanggung_jawab text not null,
  unit text not null,
  tanggal_update date not null,
  prioritas text not null,
  file_ref text,
  deskripsi text,
  created_at timestamptz not null default now()
);

create table if not exists inventaris_kebutuhan (
  id_kebutuhan text primary key,
  kelompok_dokumen text not null,
  nama_dokumen text not null,
  ketersediaan text not null,
  tingkat_kebutuhan text not null,
  gap integer not null default 0,
  prioritas_tindak_lanjut text,
  target_selesai date,
  pic text,
  catatan_gap_analysis text,
  created_at timestamptz not null default now()
);

create table if not exists sop (
  id_sop text primary key,
  kode_sop text not null unique,
  judul_sop text not null,
  tujuan text,
  ruang_lingkup text,
  ringkasan_langkah text,
  status text,
  versi text,
  pic text,
  review_berikutnya date,
  created_at timestamptz not null default now()
);

create table if not exists modul_k3 (
  id_modul text primary key,
  judul_modul text not null,
  materi_pokok text,
  sasaran text,
  durasi_menit integer,
  metode text,
  status text,
  penanggung_jawab text,
  catatan text,
  created_at timestamptz not null default now()
);

create table if not exists instruksi_kerja (
  id_ik text primary key,
  kode_ik text not null unique,
  judul_instruksi text not null,
  langkah_utama text,
  alat_terkait text,
  apd_wajib text,
  status text,
  pic text,
  catatan text,
  created_at timestamptz not null default now()
);

create table if not exists logbook (
  id bigint generated by default as identity primary key,
  tanggal date not null,
  laboratorium text not null,
  kegiatan text not null,
  petugas text not null,
  status_kegiatan text not null,
  temuan_kendala text,
  tindak_lanjut text,
  verifikator text not null,
  created_at timestamptz not null default now()
);

create table if not exists evaluasi (
  id_evaluasi text primary key,
  tanggal date not null,
  unit text not null,
  aspek text not null,
  skor integer not null check (skor between 0 and 100),
  kategori text not null,
  rekomendasi text,
  reviewer text not null,
  created_at timestamptz not null default now()
);

create table if not exists panduan (
  id bigint generated by default as identity primary key,
  bagian text not null,
  isi text not null,
  urutan integer not null default 0,
  created_at timestamptz not null default now()
);

alter table dokumen_inti enable row level security;
alter table inventaris_kebutuhan enable row level security;
alter table sop enable row level security;
alter table modul_k3 enable row level security;
alter table instruksi_kerja enable row level security;
alter table logbook enable row level security;
alter table evaluasi enable row level security;
alter table panduan enable row level security;

-- For this app, the Streamlit backend uses the service role key,
-- so RLS is bypassed server-side. These read policies are useful if you later switch to anon access.
do $$ begin
  if not exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'dokumen_inti' and policyname = 'public read dokumen_inti') then
    create policy "public read dokumen_inti" on dokumen_inti for select using (true);
  end if;
  if not exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'inventaris_kebutuhan' and policyname = 'public read inventaris_kebutuhan') then
    create policy "public read inventaris_kebutuhan" on inventaris_kebutuhan for select using (true);
  end if;
  if not exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'sop' and policyname = 'public read sop') then
    create policy "public read sop" on sop for select using (true);
  end if;
  if not exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'modul_k3' and policyname = 'public read modul_k3') then
    create policy "public read modul_k3" on modul_k3 for select using (true);
  end if;
  if not exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'instruksi_kerja' and policyname = 'public read instruksi_kerja') then
    create policy "public read instruksi_kerja" on instruksi_kerja for select using (true);
  end if;
  if not exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'logbook' and policyname = 'public read logbook') then
    create policy "public read logbook" on logbook for select using (true);
  end if;
  if not exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'evaluasi' and policyname = 'public read evaluasi') then
    create policy "public read evaluasi" on evaluasi for select using (true);
  end if;
  if not exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'panduan' and policyname = 'public read panduan') then
    create policy "public read panduan" on panduan for select using (true);
  end if;
end $$;

insert into panduan (bagian, isi, urutan) values
('Mulai Cepat', 'Masuk ke aplikasi lalu pilih tugas utama di sidebar: Beranda & Prioritas, Cari & Buka Dokumen, Cek Gap & Tindak Lanjut, Input Harian, atau Evaluasi.', 1),
('Pencarian', 'Gunakan kolom pencarian global untuk menemukan SOP, modul K3, instruksi kerja, dan metadata dokumen dari satu tempat.', 2),
('Aksi Cepat Admin', 'Admin dapat menambah dokumen, input logbook, dan input evaluasi langsung dari aplikasi tanpa edit file Excel manual.', 3)
on conflict do nothing;
